site_name: Twingle API
repo_url: https://github.com/systopia/de.systopia.twingle
theme:
  name: material

nav:
  - Introduction: index.md
  - Installation: installation.md
  - Configuration:
      - User, permissions and API authentication: configuration/user_permissions.md
      - Extended Contact Manager (XCM) extension: configuration/xcm.md
      - CiviSEPA integration: configuration/civisepa.md
      - Twingle Profiles: configuration/profiles.md
      - Configuring the Twingle Account on the Twingle website: configuration/account.md
  - API documentation: api.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - pymdownx.highlight:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

plugins:
  - search:
      lang: en